#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportMonthResultGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Diogen")]
	public partial class ReportBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertReportMonthResult(ReportMonthResult instance);
    partial void UpdateReportMonthResult(ReportMonthResult instance);
    partial void DeleteReportMonthResult(ReportMonthResult instance);
    partial void InsertReportDayQSRTime(ReportDayQSRTime instance);
    partial void UpdateReportDayQSRTime(ReportDayQSRTime instance);
    partial void DeleteReportDayQSRTime(ReportDayQSRTime instance);
    partial void InsertReportWaitersPower(ReportWaitersPower instance);
    partial void UpdateReportWaitersPower(ReportWaitersPower instance);
    partial void DeleteReportWaitersPower(ReportWaitersPower instance);
    partial void InsertDishList(DishList instance);
    partial void UpdateDishList(DishList instance);
    partial void DeleteDishList(DishList instance);
    partial void InsertAlohaDepPlace(AlohaDepPlace instance);
    partial void UpdateAlohaDepPlace(AlohaDepPlace instance);
    partial void DeleteAlohaDepPlace(AlohaDepPlace instance);
    partial void InsertReportDBFDishes(ReportDBFDishes instance);
    partial void UpdateReportDBFDishes(ReportDBFDishes instance);
    partial void DeleteReportDBFDishes(ReportDBFDishes instance);
    partial void InsertReportDBFFilesComplited(ReportDBFFilesComplited instance);
    partial void UpdateReportDBFFilesComplited(ReportDBFFilesComplited instance);
    partial void DeleteReportDBFFilesComplited(ReportDBFFilesComplited instance);
    partial void InsertReportDayQSRTimeByOrders(ReportDayQSRTimeByOrders instance);
    partial void UpdateReportDayQSRTimeByOrders(ReportDayQSRTimeByOrders instance);
    partial void DeleteReportDayQSRTimeByOrders(ReportDayQSRTimeByOrders instance);
    partial void InsertReportDayResult(ReportDayResult instance);
    partial void UpdateReportDayResult(ReportDayResult instance);
    partial void DeleteReportDayResult(ReportDayResult instance);
    partial void InsertReportTypeIds(ReportTypeIds instance);
    partial void UpdateReportTypeIds(ReportTypeIds instance);
    partial void DeleteReportTypeIds(ReportTypeIds instance);
    partial void InsertAlohaMenuItemsAll(AlohaMenuItemsAll instance);
    partial void UpdateAlohaMenuItemsAll(AlohaMenuItemsAll instance);
    partial void DeleteAlohaMenuItemsAll(AlohaMenuItemsAll instance);
    partial void InsertAlohaMenuCatAll(AlohaMenuCatAll instance);
    partial void UpdateAlohaMenuCatAll(AlohaMenuCatAll instance);
    partial void DeleteAlohaMenuCatAll(AlohaMenuCatAll instance);
    partial void InsertAlohaMenuComps(AlohaMenuComps instance);
    partial void UpdateAlohaMenuComps(AlohaMenuComps instance);
    partial void DeleteAlohaMenuComps(AlohaMenuComps instance);
    partial void InsertOrderTimes(OrderTimes instance);
    partial void UpdateOrderTimes(OrderTimes instance);
    partial void DeleteOrderTimes(OrderTimes instance);
    #endregion
		
		public ReportBaseDataContext() : 
				base(global::ReportMonthResultGenerator.Properties.Settings.Default.DiogenConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ReportBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReportMonthResult> ReportMonthResults
		{
			get
			{
				return this.GetTable<ReportMonthResult>();
			}
		}
		
		public System.Data.Linq.Table<AlohaMenuITM> AlohaMenuITMs
		{
			get
			{
				return this.GetTable<AlohaMenuITM>();
			}
		}
		
		public System.Data.Linq.Table<AlohaMenuItemCatsLink> AlohaMenuItemCatsLinks
		{
			get
			{
				return this.GetTable<AlohaMenuItemCatsLink>();
			}
		}
		
		public System.Data.Linq.Table<ReportDayQSRTime> ReportDayQSRTimes
		{
			get
			{
				return this.GetTable<ReportDayQSRTime>();
			}
		}
		
		public System.Data.Linq.Table<ReportWaitersPower> ReportWaitersPowers
		{
			get
			{
				return this.GetTable<ReportWaitersPower>();
			}
		}
		
		public System.Data.Linq.Table<DishList> DishLists
		{
			get
			{
				return this.GetTable<DishList>();
			}
		}
		
		public System.Data.Linq.Table<GuestCount> GuestCounts
		{
			get
			{
				return this.GetTable<GuestCount>();
			}
		}
		
		public System.Data.Linq.Table<AlohaDepPlace> AlohaDepPlaces
		{
			get
			{
				return this.GetTable<AlohaDepPlace>();
			}
		}
		
		public System.Data.Linq.Table<ReportDBFDishes> ReportDBFDishes
		{
			get
			{
				return this.GetTable<ReportDBFDishes>();
			}
		}
		
		public System.Data.Linq.Table<ReportDBFFilesComplited> ReportDBFFilesComplited
		{
			get
			{
				return this.GetTable<ReportDBFFilesComplited>();
			}
		}
		
		public System.Data.Linq.Table<ReportDayQSRTimeByOrders> ReportDayQSRTimeByOrders
		{
			get
			{
				return this.GetTable<ReportDayQSRTimeByOrders>();
			}
		}
		
		public System.Data.Linq.Table<ReportDayResult> ReportDayResult
		{
			get
			{
				return this.GetTable<ReportDayResult>();
			}
		}
		
		public System.Data.Linq.Table<ReportTypeIds> ReportTypeIds
		{
			get
			{
				return this.GetTable<ReportTypeIds>();
			}
		}
		
		public System.Data.Linq.Table<AlohaMenuItemsAll> AlohaMenuItemsAll
		{
			get
			{
				return this.GetTable<AlohaMenuItemsAll>();
			}
		}
		
		public System.Data.Linq.Table<AlohaMenuCatAll> AlohaMenuCatAll
		{
			get
			{
				return this.GetTable<AlohaMenuCatAll>();
			}
		}
		
		public System.Data.Linq.Table<AlohaMenuComps> AlohaMenuComps
		{
			get
			{
				return this.GetTable<AlohaMenuComps>();
			}
		}
		
		public System.Data.Linq.Table<OrderTimes> OrderTimes
		{
			get
			{
				return this.GetTable<OrderTimes>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DiffTime4", IsComposable=true)]
		public System.Nullable<int> DiffTime4([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DayStart", DbType="DateTime")] System.Nullable<System.DateTime> dayStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DayEnd", DbType="DateTime")] System.Nullable<System.DateTime> dayEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepNum", DbType="Int")] System.Nullable<int> depNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DishNum", DbType="BigInt")] System.Nullable<long> dishNum)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dayStart, dayEnd, depNum, dishNum).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportMonthResult")]
	public partial class ReportMonthResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Month;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<double> _Value;
		
		private System.Nullable<int> _Department;
		
		private System.Nullable<double> _Value2;
		
		private System.Nullable<double> _Value3;
		
		private string _DepName;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMonthChanging(System.Nullable<System.DateTime> value);
    partial void OnMonthChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnValueChanging(System.Nullable<double> value);
    partial void OnValueChanged();
    partial void OnDepartmentChanging(System.Nullable<int> value);
    partial void OnDepartmentChanged();
    partial void OnValue2Changing(System.Nullable<double> value);
    partial void OnValue2Changed();
    partial void OnValue3Changing(System.Nullable<double> value);
    partial void OnValue3Changed();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    #endregion
		
		public ReportMonthResult()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Date")]
		public System.Nullable<System.DateTime> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
		public System.Nullable<int> Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value2", DbType="Float")]
		public System.Nullable<double> Value2
		{
			get
			{
				return this._Value2;
			}
			set
			{
				if ((this._Value2 != value))
				{
					this.OnValue2Changing(value);
					this.SendPropertyChanging();
					this._Value2 = value;
					this.SendPropertyChanged("Value2");
					this.OnValue2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value3", DbType="Float")]
		public System.Nullable<double> Value3
		{
			get
			{
				return this._Value3;
			}
			set
			{
				if ((this._Value3 != value))
				{
					this.OnValue3Changing(value);
					this.SendPropertyChanging();
					this._Value3 = value;
					this.SendPropertyChanged("Value3");
					this.OnValue3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NChar(50)")]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaMenuITM")]
	public partial class AlohaMenuITM
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _DELAYTIME;
		
		private System.Nullable<int> _Dep;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _Category;
		
		private string _Name;
		
		public AlohaMenuITM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELAYTIME", DbType="Int")]
		public System.Nullable<int> DELAYTIME
		{
			get
			{
				return this._DELAYTIME;
			}
			set
			{
				if ((this._DELAYTIME != value))
				{
					this._DELAYTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="Int")]
		public System.Nullable<int> Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this._Dep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int")]
		public System.Nullable<int> Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaMenuItemCatsLink")]
	public partial class AlohaMenuItemCatsLink
	{
		
		private int _ID;
		
		private System.Nullable<int> _BarCode;
		
		private System.Nullable<int> _CatNum;
		
		private System.Nullable<int> _DepId;
		
		public AlohaMenuItemCatsLink()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="Int")]
		public System.Nullable<int> BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this._BarCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNum", DbType="Int")]
		public System.Nullable<int> CatNum
		{
			get
			{
				return this._CatNum;
			}
			set
			{
				if ((this._CatNum != value))
				{
					this._CatNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepId", DbType="Int")]
		public System.Nullable<int> DepId
		{
			get
			{
				return this._DepId;
			}
			set
			{
				if ((this._DepId != value))
				{
					this._DepId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportDayQSRTime")]
	public partial class ReportDayQSRTime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _Day;
		
		private System.Nullable<int> _OrdersCount;
		
		private System.Nullable<int> _WrongCount;
		
		private System.Nullable<int> _AllTime;
		
		private System.Nullable<int> _WrongTime;
		
		private System.Nullable<int> _Department;
		
		private System.Nullable<int> _EmpId;
		
		private string _EmpName;
		
		private System.Nullable<int> _FactSummOfWrong;
		
		private System.Nullable<int> _NormaSummOfWrong;
		
		private int _Id;
		
		private string _DepName;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDayChanging(System.Nullable<System.DateTime> value);
    partial void OnDayChanged();
    partial void OnOrdersCountChanging(System.Nullable<int> value);
    partial void OnOrdersCountChanged();
    partial void OnWrongCountChanging(System.Nullable<int> value);
    partial void OnWrongCountChanged();
    partial void OnAllTimeChanging(System.Nullable<int> value);
    partial void OnAllTimeChanged();
    partial void OnWrongTimeChanging(System.Nullable<int> value);
    partial void OnWrongTimeChanged();
    partial void OnDepartmentChanging(System.Nullable<int> value);
    partial void OnDepartmentChanged();
    partial void OnEmpIdChanging(System.Nullable<int> value);
    partial void OnEmpIdChanged();
    partial void OnEmpNameChanging(string value);
    partial void OnEmpNameChanged();
    partial void OnFactSummOfWrongChanging(System.Nullable<int> value);
    partial void OnFactSummOfWrongChanged();
    partial void OnNormaSummOfWrongChanging(System.Nullable<int> value);
    partial void OnNormaSummOfWrongChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    #endregion
		
		public ReportDayQSRTime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Date")]
		public System.Nullable<System.DateTime> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdersCount", DbType="Int")]
		public System.Nullable<int> OrdersCount
		{
			get
			{
				return this._OrdersCount;
			}
			set
			{
				if ((this._OrdersCount != value))
				{
					this.OnOrdersCountChanging(value);
					this.SendPropertyChanging();
					this._OrdersCount = value;
					this.SendPropertyChanged("OrdersCount");
					this.OnOrdersCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WrongCount", DbType="Int")]
		public System.Nullable<int> WrongCount
		{
			get
			{
				return this._WrongCount;
			}
			set
			{
				if ((this._WrongCount != value))
				{
					this.OnWrongCountChanging(value);
					this.SendPropertyChanging();
					this._WrongCount = value;
					this.SendPropertyChanged("WrongCount");
					this.OnWrongCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllTime", DbType="Int")]
		public System.Nullable<int> AllTime
		{
			get
			{
				return this._AllTime;
			}
			set
			{
				if ((this._AllTime != value))
				{
					this.OnAllTimeChanging(value);
					this.SendPropertyChanging();
					this._AllTime = value;
					this.SendPropertyChanged("AllTime");
					this.OnAllTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WrongTime", DbType="Int")]
		public System.Nullable<int> WrongTime
		{
			get
			{
				return this._WrongTime;
			}
			set
			{
				if ((this._WrongTime != value))
				{
					this.OnWrongTimeChanging(value);
					this.SendPropertyChanging();
					this._WrongTime = value;
					this.SendPropertyChanged("WrongTime");
					this.OnWrongTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
		public System.Nullable<int> Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="Int")]
		public System.Nullable<int> EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpName", DbType="NChar(50)")]
		public string EmpName
		{
			get
			{
				return this._EmpName;
			}
			set
			{
				if ((this._EmpName != value))
				{
					this.OnEmpNameChanging(value);
					this.SendPropertyChanging();
					this._EmpName = value;
					this.SendPropertyChanged("EmpName");
					this.OnEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactSummOfWrong", DbType="Int")]
		public System.Nullable<int> FactSummOfWrong
		{
			get
			{
				return this._FactSummOfWrong;
			}
			set
			{
				if ((this._FactSummOfWrong != value))
				{
					this.OnFactSummOfWrongChanging(value);
					this.SendPropertyChanging();
					this._FactSummOfWrong = value;
					this.SendPropertyChanged("FactSummOfWrong");
					this.OnFactSummOfWrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormaSummOfWrong", DbType="Int")]
		public System.Nullable<int> NormaSummOfWrong
		{
			get
			{
				return this._NormaSummOfWrong;
			}
			set
			{
				if ((this._NormaSummOfWrong != value))
				{
					this.OnNormaSummOfWrongChanging(value);
					this.SendPropertyChanging();
					this._NormaSummOfWrong = value;
					this.SendPropertyChanged("NormaSummOfWrong");
					this.OnNormaSummOfWrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NChar(50)")]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportWaitersPower")]
	public partial class ReportWaitersPower : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _dt;
		
		private System.Nullable<int> _Dep;
		
		private System.Nullable<double> _Waiters;
		
		private System.Nullable<double> _Checks;
		
		private System.Nullable<int> _DayOfWeak;
		
		private string _TimeOfDay;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OndtChanging(System.Nullable<System.DateTime> value);
    partial void OndtChanged();
    partial void OnDepChanging(System.Nullable<int> value);
    partial void OnDepChanged();
    partial void OnWaitersChanging(System.Nullable<double> value);
    partial void OnWaitersChanged();
    partial void OnChecksChanging(System.Nullable<double> value);
    partial void OnChecksChanged();
    partial void OnDayOfWeakChanging(System.Nullable<int> value);
    partial void OnDayOfWeakChanged();
    partial void OnTimeOfDayChanging(string value);
    partial void OnTimeOfDayChanged();
    #endregion
		
		public ReportWaitersPower()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this.OndtChanging(value);
					this.SendPropertyChanging();
					this._dt = value;
					this.SendPropertyChanged("dt");
					this.OndtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="Int")]
		public System.Nullable<int> Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this.OnDepChanging(value);
					this.SendPropertyChanging();
					this._Dep = value;
					this.SendPropertyChanged("Dep");
					this.OnDepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Waiters", DbType="Float")]
		public System.Nullable<double> Waiters
		{
			get
			{
				return this._Waiters;
			}
			set
			{
				if ((this._Waiters != value))
				{
					this.OnWaitersChanging(value);
					this.SendPropertyChanging();
					this._Waiters = value;
					this.SendPropertyChanged("Waiters");
					this.OnWaitersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checks", DbType="Float")]
		public System.Nullable<double> Checks
		{
			get
			{
				return this._Checks;
			}
			set
			{
				if ((this._Checks != value))
				{
					this.OnChecksChanging(value);
					this.SendPropertyChanging();
					this._Checks = value;
					this.SendPropertyChanged("Checks");
					this.OnChecksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayOfWeak", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DayOfWeak
		{
			get
			{
				return this._DayOfWeak;
			}
			set
			{
				if ((this._DayOfWeak != value))
				{
					this.OnDayOfWeakChanging(value);
					this.SendPropertyChanging();
					this._DayOfWeak = value;
					this.SendPropertyChanged("DayOfWeak");
					this.OnDayOfWeakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOfDay", AutoSync=AutoSync.Always, DbType="VarChar(5)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string TimeOfDay
		{
			get
			{
				return this._TimeOfDay;
			}
			set
			{
				if ((this._TimeOfDay != value))
				{
					this.OnTimeOfDayChanging(value);
					this.SendPropertyChanging();
					this._TimeOfDay = value;
					this.SendPropertyChanged("TimeOfDay");
					this.OnTimeOfDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DishList")]
	public partial class DishList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DishName;
		
		private long _DishBarCode;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDishNameChanging(string value);
    partial void OnDishNameChanged();
    partial void OnDishBarCodeChanging(long value);
    partial void OnDishBarCodeChanged();
    #endregion
		
		public DishList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DishName", DbType="NChar(100)")]
		public string DishName
		{
			get
			{
				return this._DishName;
			}
			set
			{
				if ((this._DishName != value))
				{
					this.OnDishNameChanging(value);
					this.SendPropertyChanging();
					this._DishName = value;
					this.SendPropertyChanged("DishName");
					this.OnDishNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DishBarCode", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long DishBarCode
		{
			get
			{
				return this._DishBarCode;
			}
			set
			{
				if ((this._DishBarCode != value))
				{
					this.OnDishBarCodeChanging(value);
					this.SendPropertyChanging();
					this._DishBarCode = value;
					this.SendPropertyChanged("DishBarCode");
					this.OnDishBarCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GuestCount")]
	public partial class GuestCount
	{
		
		private System.Nullable<int> _GuestCount1;
		
		private System.Nullable<long> _CheckLongNum;
		
		private System.Nullable<System.DateTime> _SystemDateOfOpen;
		
		private System.Nullable<System.DateTime> _SystemDate;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
		private System.Nullable<long> _AlohaCheckNum;
		
		private long _UnId;
		
		private System.Nullable<int> _DepNum;
		
		public GuestCount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="GuestCount", Storage="_GuestCount1", DbType="Int")]
		public System.Nullable<int> GuestCount1
		{
			get
			{
				return this._GuestCount1;
			}
			set
			{
				if ((this._GuestCount1 != value))
				{
					this._GuestCount1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckLongNum", DbType="BigInt")]
		public System.Nullable<long> CheckLongNum
		{
			get
			{
				return this._CheckLongNum;
			}
			set
			{
				if ((this._CheckLongNum != value))
				{
					this._CheckLongNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemDateOfOpen", DbType="DateTime")]
		public System.Nullable<System.DateTime> SystemDateOfOpen
		{
			get
			{
				return this._SystemDateOfOpen;
			}
			set
			{
				if ((this._SystemDateOfOpen != value))
				{
					this._SystemDateOfOpen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SystemDate
		{
			get
			{
				return this._SystemDate;
			}
			set
			{
				if ((this._SystemDate != value))
				{
					this._SystemDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this._BusinessDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlohaCheckNum", DbType="BigInt")]
		public System.Nullable<long> AlohaCheckNum
		{
			get
			{
				return this._AlohaCheckNum;
			}
			set
			{
				if ((this._AlohaCheckNum != value))
				{
					this._AlohaCheckNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnId", DbType="BigInt NOT NULL")]
		public long UnId
		{
			get
			{
				return this._UnId;
			}
			set
			{
				if ((this._UnId != value))
				{
					this._UnId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNum", DbType="Int")]
		public System.Nullable<int> DepNum
		{
			get
			{
				return this._DepNum;
			}
			set
			{
				if ((this._DepNum != value))
				{
					this._DepNum = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaDepPlaces")]
	public partial class AlohaDepPlace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DepNum;
		
		private System.Nullable<int> _PosMest;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepNumChanging(int value);
    partial void OnDepNumChanged();
    partial void OnPosMestChanging(System.Nullable<int> value);
    partial void OnPosMestChanged();
    #endregion
		
		public AlohaDepPlace()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNum", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DepNum
		{
			get
			{
				return this._DepNum;
			}
			set
			{
				if ((this._DepNum != value))
				{
					this.OnDepNumChanging(value);
					this.SendPropertyChanging();
					this._DepNum = value;
					this.SendPropertyChanged("DepNum");
					this.OnDepNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosMest", DbType="Int")]
		public System.Nullable<int> PosMest
		{
			get
			{
				return this._PosMest;
			}
			set
			{
				if ((this._PosMest != value))
				{
					this.OnPosMestChanging(value);
					this.SendPropertyChanging();
					this._PosMest = value;
					this.SendPropertyChanged("PosMest");
					this.OnPosMestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportDBFDishes")]
	public partial class ReportDBFDishes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CheckId;
		
		private System.Nullable<int> _BarCode;
		
		private System.Nullable<System.DateTime> _OrderTime;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
		private System.Nullable<int> _Dep;
		
		private System.Nullable<int> _Empl;
		
		private System.Nullable<int> _EntryId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCheckIdChanging(System.Nullable<int> value);
    partial void OnCheckIdChanged();
    partial void OnBarCodeChanging(System.Nullable<int> value);
    partial void OnBarCodeChanged();
    partial void OnOrderTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderTimeChanged();
    partial void OnBusinessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBusinessDateChanged();
    partial void OnDepChanging(System.Nullable<int> value);
    partial void OnDepChanged();
    partial void OnEmplChanging(System.Nullable<int> value);
    partial void OnEmplChanged();
    partial void OnEntryIdChanging(System.Nullable<int> value);
    partial void OnEntryIdChanged();
    #endregion
		
		public ReportDBFDishes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckId", DbType="Int")]
		public System.Nullable<int> CheckId
		{
			get
			{
				return this._CheckId;
			}
			set
			{
				if ((this._CheckId != value))
				{
					this.OnCheckIdChanging(value);
					this.SendPropertyChanging();
					this._CheckId = value;
					this.SendPropertyChanged("CheckId");
					this.OnCheckIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="Int")]
		public System.Nullable<int> BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderTime
		{
			get
			{
				return this._OrderTime;
			}
			set
			{
				if ((this._OrderTime != value))
				{
					this.OnOrderTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderTime = value;
					this.SendPropertyChanged("OrderTime");
					this.OnOrderTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="Int")]
		public System.Nullable<int> Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this.OnDepChanging(value);
					this.SendPropertyChanging();
					this._Dep = value;
					this.SendPropertyChanged("Dep");
					this.OnDepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empl", DbType="Int")]
		public System.Nullable<int> Empl
		{
			get
			{
				return this._Empl;
			}
			set
			{
				if ((this._Empl != value))
				{
					this.OnEmplChanging(value);
					this.SendPropertyChanging();
					this._Empl = value;
					this.SendPropertyChanged("Empl");
					this.OnEmplChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryId", DbType="Int")]
		public System.Nullable<int> EntryId
		{
			get
			{
				return this._EntryId;
			}
			set
			{
				if ((this._EntryId != value))
				{
					this.OnEntryIdChanging(value);
					this.SendPropertyChanging();
					this._EntryId = value;
					this.SendPropertyChanged("EntryId");
					this.OnEntryIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportDBFFilesComplited")]
	public partial class ReportDBFFilesComplited : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FileName;
		
		private string _Dep;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnDepChanging(string value);
    partial void OnDepChanged();
    #endregion
		
		public ReportDBFFilesComplited()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="NChar(100)")]
		public string Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this.OnDepChanging(value);
					this.SendPropertyChanging();
					this._Dep = value;
					this.SendPropertyChanged("Dep");
					this.OnDepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportDayQSRTimeByOrders")]
	public partial class ReportDayQSRTimeByOrders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _Day;
		
		private System.Nullable<int> _OrdersCount;
		
		private System.Nullable<int> _WrongCount;
		
		private System.Nullable<int> _AllTime;
		
		private System.Nullable<int> _WrongTime;
		
		private System.Nullable<int> _Department;
		
		private System.Nullable<int> _EmpId;
		
		private string _EmpName;
		
		private System.Nullable<int> _FactSummOfWrong;
		
		private System.Nullable<int> _NormaSummOfWrong;
		
		private int _Id;
		
		private string _DepName;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDayChanging(System.Nullable<System.DateTime> value);
    partial void OnDayChanged();
    partial void OnOrdersCountChanging(System.Nullable<int> value);
    partial void OnOrdersCountChanged();
    partial void OnWrongCountChanging(System.Nullable<int> value);
    partial void OnWrongCountChanged();
    partial void OnAllTimeChanging(System.Nullable<int> value);
    partial void OnAllTimeChanged();
    partial void OnWrongTimeChanging(System.Nullable<int> value);
    partial void OnWrongTimeChanged();
    partial void OnDepartmentChanging(System.Nullable<int> value);
    partial void OnDepartmentChanged();
    partial void OnEmpIdChanging(System.Nullable<int> value);
    partial void OnEmpIdChanged();
    partial void OnEmpNameChanging(string value);
    partial void OnEmpNameChanged();
    partial void OnFactSummOfWrongChanging(System.Nullable<int> value);
    partial void OnFactSummOfWrongChanged();
    partial void OnNormaSummOfWrongChanging(System.Nullable<int> value);
    partial void OnNormaSummOfWrongChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    #endregion
		
		public ReportDayQSRTimeByOrders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Date")]
		public System.Nullable<System.DateTime> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdersCount", DbType="Int")]
		public System.Nullable<int> OrdersCount
		{
			get
			{
				return this._OrdersCount;
			}
			set
			{
				if ((this._OrdersCount != value))
				{
					this.OnOrdersCountChanging(value);
					this.SendPropertyChanging();
					this._OrdersCount = value;
					this.SendPropertyChanged("OrdersCount");
					this.OnOrdersCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WrongCount", DbType="Int")]
		public System.Nullable<int> WrongCount
		{
			get
			{
				return this._WrongCount;
			}
			set
			{
				if ((this._WrongCount != value))
				{
					this.OnWrongCountChanging(value);
					this.SendPropertyChanging();
					this._WrongCount = value;
					this.SendPropertyChanged("WrongCount");
					this.OnWrongCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllTime", DbType="Int")]
		public System.Nullable<int> AllTime
		{
			get
			{
				return this._AllTime;
			}
			set
			{
				if ((this._AllTime != value))
				{
					this.OnAllTimeChanging(value);
					this.SendPropertyChanging();
					this._AllTime = value;
					this.SendPropertyChanged("AllTime");
					this.OnAllTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WrongTime", DbType="Int")]
		public System.Nullable<int> WrongTime
		{
			get
			{
				return this._WrongTime;
			}
			set
			{
				if ((this._WrongTime != value))
				{
					this.OnWrongTimeChanging(value);
					this.SendPropertyChanging();
					this._WrongTime = value;
					this.SendPropertyChanged("WrongTime");
					this.OnWrongTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
		public System.Nullable<int> Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="Int")]
		public System.Nullable<int> EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpName", DbType="NChar(50)")]
		public string EmpName
		{
			get
			{
				return this._EmpName;
			}
			set
			{
				if ((this._EmpName != value))
				{
					this.OnEmpNameChanging(value);
					this.SendPropertyChanging();
					this._EmpName = value;
					this.SendPropertyChanged("EmpName");
					this.OnEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactSummOfWrong", DbType="Int")]
		public System.Nullable<int> FactSummOfWrong
		{
			get
			{
				return this._FactSummOfWrong;
			}
			set
			{
				if ((this._FactSummOfWrong != value))
				{
					this.OnFactSummOfWrongChanging(value);
					this.SendPropertyChanging();
					this._FactSummOfWrong = value;
					this.SendPropertyChanged("FactSummOfWrong");
					this.OnFactSummOfWrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormaSummOfWrong", DbType="Int")]
		public System.Nullable<int> NormaSummOfWrong
		{
			get
			{
				return this._NormaSummOfWrong;
			}
			set
			{
				if ((this._NormaSummOfWrong != value))
				{
					this.OnNormaSummOfWrongChanging(value);
					this.SendPropertyChanging();
					this._NormaSummOfWrong = value;
					this.SendPropertyChanged("NormaSummOfWrong");
					this.OnNormaSummOfWrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NChar(50)")]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportDayResult")]
	public partial class ReportDayResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _BD;
		
		private System.Nullable<int> _TypeId;
		
		private System.Nullable<double> _Value;
		
		private System.Nullable<int> _Dep;
		
		private System.Nullable<double> _Summ;
		
		private System.Nullable<double> _Count;
		
		private string _DepName;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBDChanging(System.Nullable<System.DateTime> value);
    partial void OnBDChanged();
    partial void OnTypeIdChanging(System.Nullable<int> value);
    partial void OnTypeIdChanged();
    partial void OnValueChanging(System.Nullable<double> value);
    partial void OnValueChanged();
    partial void OnDepChanging(System.Nullable<int> value);
    partial void OnDepChanged();
    partial void OnSummChanging(System.Nullable<double> value);
    partial void OnSummChanged();
    partial void OnCountChanging(System.Nullable<double> value);
    partial void OnCountChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    #endregion
		
		public ReportDayResult()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BD", DbType="Date")]
		public System.Nullable<System.DateTime> BD
		{
			get
			{
				return this._BD;
			}
			set
			{
				if ((this._BD != value))
				{
					this.OnBDChanging(value);
					this.SendPropertyChanging();
					this._BD = value;
					this.SendPropertyChanged("BD");
					this.OnBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", DbType="Int")]
		public System.Nullable<int> TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="Int")]
		public System.Nullable<int> Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this.OnDepChanging(value);
					this.SendPropertyChanging();
					this._Dep = value;
					this.SendPropertyChanged("Dep");
					this.OnDepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summ", DbType="Float")]
		public System.Nullable<double> Summ
		{
			get
			{
				return this._Summ;
			}
			set
			{
				if ((this._Summ != value))
				{
					this.OnSummChanging(value);
					this.SendPropertyChanging();
					this._Summ = value;
					this.SendPropertyChanged("Summ");
					this.OnSummChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", DbType="Float")]
		public System.Nullable<double> Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NChar(50)")]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportTypeIds")]
	public partial class ReportTypeIds : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TypeId;
		
		private string _Caption;
		
		private bool _Enable;
		
		private string _TypeSystemName;
		
		private string _Format;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTypeIdChanging(int value);
    partial void OnTypeIdChanged();
    partial void OnCaptionChanging(string value);
    partial void OnCaptionChanged();
    partial void OnEnableChanging(bool value);
    partial void OnEnableChanged();
    partial void OnTypeSystemNameChanging(string value);
    partial void OnTypeSystemNameChanged();
    partial void OnFormatChanging(string value);
    partial void OnFormatChanged();
    #endregion
		
		public ReportTypeIds()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TypeId
		{
			get
			{
				return this._TypeId;
			}
			set
			{
				if ((this._TypeId != value))
				{
					this.OnTypeIdChanging(value);
					this.SendPropertyChanging();
					this._TypeId = value;
					this.SendPropertyChanged("TypeId");
					this.OnTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this.OnCaptionChanging(value);
					this.SendPropertyChanging();
					this._Caption = value;
					this.SendPropertyChanged("Caption");
					this.OnCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enable", DbType="Bit NOT NULL")]
		public bool Enable
		{
			get
			{
				return this._Enable;
			}
			set
			{
				if ((this._Enable != value))
				{
					this.OnEnableChanging(value);
					this.SendPropertyChanging();
					this._Enable = value;
					this.SendPropertyChanged("Enable");
					this.OnEnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeSystemName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TypeSystemName
		{
			get
			{
				return this._TypeSystemName;
			}
			set
			{
				if ((this._TypeSystemName != value))
				{
					this.OnTypeSystemNameChanging(value);
					this.SendPropertyChanging();
					this._TypeSystemName = value;
					this.SendPropertyChanged("TypeSystemName");
					this.OnTypeSystemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Format", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Format
		{
			get
			{
				return this._Format;
			}
			set
			{
				if ((this._Format != value))
				{
					this.OnFormatChanging(value);
					this.SendPropertyChanging();
					this._Format = value;
					this.SendPropertyChanged("Format");
					this.OnFormatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaMenuItemsAll")]
	public partial class AlohaMenuItemsAll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _BarCode;
		
		private string _Name;
		
		private int _CategoryId;
		
		private bool _IsDish;
		
		private bool _IsDrink;
		
		private int _Weight;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBarCodeChanging(int value);
    partial void OnBarCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnIsDishChanging(bool value);
    partial void OnIsDishChanged();
    partial void OnIsDrinkChanging(bool value);
    partial void OnIsDrinkChanged();
    partial void OnWeightChanging(int value);
    partial void OnWeightChanged();
    #endregion
		
		public AlohaMenuItemsAll()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="Int NOT NULL")]
		public int BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int NOT NULL")]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDish", DbType="Bit NOT NULL")]
		public bool IsDish
		{
			get
			{
				return this._IsDish;
			}
			set
			{
				if ((this._IsDish != value))
				{
					this.OnIsDishChanging(value);
					this.SendPropertyChanging();
					this._IsDish = value;
					this.SendPropertyChanged("IsDish");
					this.OnIsDishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDrink", DbType="Bit NOT NULL")]
		public bool IsDrink
		{
			get
			{
				return this._IsDrink;
			}
			set
			{
				if ((this._IsDrink != value))
				{
					this.OnIsDrinkChanging(value);
					this.SendPropertyChanging();
					this._IsDrink = value;
					this.SendPropertyChanged("IsDrink");
					this.OnIsDrinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int NOT NULL")]
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaMenuCatAll")]
	public partial class AlohaMenuCatAll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cat;
		
		private string _Name;
		
		private int _Id;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCatChanging(int value);
    partial void OnCatChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public AlohaMenuCatAll()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat", DbType="Int NOT NULL")]
		public int Cat
		{
			get
			{
				return this._Cat;
			}
			set
			{
				if ((this._Cat != value))
				{
					this.OnCatChanging(value);
					this.SendPropertyChanging();
					this._Cat = value;
					this.SendPropertyChanged("Cat");
					this.OnCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlohaMenuComps")]
	public partial class AlohaMenuComps : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _AlohaCompId;
		
		private string _Name;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAlohaCompIdChanging(int value);
    partial void OnAlohaCompIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public AlohaMenuComps()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlohaCompId", DbType="Int NOT NULL")]
		public int AlohaCompId
		{
			get
			{
				return this._AlohaCompId;
			}
			set
			{
				if ((this._AlohaCompId != value))
				{
					this.OnAlohaCompIdChanging(value);
					this.SendPropertyChanging();
					this._AlohaCompId = value;
					this.SendPropertyChanged("AlohaCompId");
					this.OnAlohaCompIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderTimes")]
	public partial class OrderTimes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<int> _ItemCookTime;
		
		private System.Nullable<int> _TransactionNumber;
		
		private System.Nullable<int> _ItemNumber;
		
		private System.Nullable<int> _ItemId;
		
		private System.Nullable<int> _OrderFirstDisplayedTime;
		
		private System.Nullable<int> _OrderLastBumpTime;
		
		private System.Nullable<int> _VirtualDisplayId;
		
		private System.Nullable<int> _ServerId;
		
		private System.Nullable<System.DateTime> _OrderStartTime;
		
		private System.Nullable<int> _Dep;
		
		private System.Nullable<System.DateTime> _BusinessDate;
		
		private System.Nullable<System.DateTime> _OrderEndTime;
		
		private System.Nullable<int> _TableNum;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnItemCookTimeChanging(System.Nullable<int> value);
    partial void OnItemCookTimeChanged();
    partial void OnTransactionNumberChanging(System.Nullable<int> value);
    partial void OnTransactionNumberChanged();
    partial void OnItemNumberChanging(System.Nullable<int> value);
    partial void OnItemNumberChanged();
    partial void OnItemIdChanging(System.Nullable<int> value);
    partial void OnItemIdChanged();
    partial void OnOrderFirstDisplayedTimeChanging(System.Nullable<int> value);
    partial void OnOrderFirstDisplayedTimeChanged();
    partial void OnOrderLastBumpTimeChanging(System.Nullable<int> value);
    partial void OnOrderLastBumpTimeChanged();
    partial void OnVirtualDisplayIdChanging(System.Nullable<int> value);
    partial void OnVirtualDisplayIdChanged();
    partial void OnServerIdChanging(System.Nullable<int> value);
    partial void OnServerIdChanged();
    partial void OnOrderStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderStartTimeChanged();
    partial void OnDepChanging(System.Nullable<int> value);
    partial void OnDepChanged();
    partial void OnBusinessDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBusinessDateChanged();
    partial void OnOrderEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderEndTimeChanged();
    partial void OnTableNumChanging(System.Nullable<int> value);
    partial void OnTableNumChanged();
    #endregion
		
		public OrderTimes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCookTime", DbType="Int")]
		public System.Nullable<int> ItemCookTime
		{
			get
			{
				return this._ItemCookTime;
			}
			set
			{
				if ((this._ItemCookTime != value))
				{
					this.OnItemCookTimeChanging(value);
					this.SendPropertyChanging();
					this._ItemCookTime = value;
					this.SendPropertyChanged("ItemCookTime");
					this.OnItemCookTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionNumber", DbType="Int")]
		public System.Nullable<int> TransactionNumber
		{
			get
			{
				return this._TransactionNumber;
			}
			set
			{
				if ((this._TransactionNumber != value))
				{
					this.OnTransactionNumberChanging(value);
					this.SendPropertyChanging();
					this._TransactionNumber = value;
					this.SendPropertyChanged("TransactionNumber");
					this.OnTransactionNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumber", DbType="Int")]
		public System.Nullable<int> ItemNumber
		{
			get
			{
				return this._ItemNumber;
			}
			set
			{
				if ((this._ItemNumber != value))
				{
					this.OnItemNumberChanging(value);
					this.SendPropertyChanging();
					this._ItemNumber = value;
					this.SendPropertyChanged("ItemNumber");
					this.OnItemNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int")]
		public System.Nullable<int> ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderFirstDisplayedTime", DbType="Int")]
		public System.Nullable<int> OrderFirstDisplayedTime
		{
			get
			{
				return this._OrderFirstDisplayedTime;
			}
			set
			{
				if ((this._OrderFirstDisplayedTime != value))
				{
					this.OnOrderFirstDisplayedTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderFirstDisplayedTime = value;
					this.SendPropertyChanged("OrderFirstDisplayedTime");
					this.OnOrderFirstDisplayedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderLastBumpTime", DbType="Int")]
		public System.Nullable<int> OrderLastBumpTime
		{
			get
			{
				return this._OrderLastBumpTime;
			}
			set
			{
				if ((this._OrderLastBumpTime != value))
				{
					this.OnOrderLastBumpTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderLastBumpTime = value;
					this.SendPropertyChanged("OrderLastBumpTime");
					this.OnOrderLastBumpTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualDisplayId", DbType="Int")]
		public System.Nullable<int> VirtualDisplayId
		{
			get
			{
				return this._VirtualDisplayId;
			}
			set
			{
				if ((this._VirtualDisplayId != value))
				{
					this.OnVirtualDisplayIdChanging(value);
					this.SendPropertyChanging();
					this._VirtualDisplayId = value;
					this.SendPropertyChanged("VirtualDisplayId");
					this.OnVirtualDisplayIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerId", DbType="Int")]
		public System.Nullable<int> ServerId
		{
			get
			{
				return this._ServerId;
			}
			set
			{
				if ((this._ServerId != value))
				{
					this.OnServerIdChanging(value);
					this.SendPropertyChanging();
					this._ServerId = value;
					this.SendPropertyChanged("ServerId");
					this.OnServerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderStartTime
		{
			get
			{
				return this._OrderStartTime;
			}
			set
			{
				if ((this._OrderStartTime != value))
				{
					this.OnOrderStartTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderStartTime = value;
					this.SendPropertyChanged("OrderStartTime");
					this.OnOrderStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dep", DbType="Int")]
		public System.Nullable<int> Dep
		{
			get
			{
				return this._Dep;
			}
			set
			{
				if ((this._Dep != value))
				{
					this.OnDepChanging(value);
					this.SendPropertyChanging();
					this._Dep = value;
					this.SendPropertyChanged("Dep");
					this.OnDepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BusinessDate
		{
			get
			{
				return this._BusinessDate;
			}
			set
			{
				if ((this._BusinessDate != value))
				{
					this.OnBusinessDateChanging(value);
					this.SendPropertyChanging();
					this._BusinessDate = value;
					this.SendPropertyChanged("BusinessDate");
					this.OnBusinessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderEndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderEndTime
		{
			get
			{
				return this._OrderEndTime;
			}
			set
			{
				if ((this._OrderEndTime != value))
				{
					this.OnOrderEndTimeChanging(value);
					this.SendPropertyChanging();
					this._OrderEndTime = value;
					this.SendPropertyChanged("OrderEndTime");
					this.OnOrderEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TableNum", DbType="Int")]
		public System.Nullable<int> TableNum
		{
			get
			{
				return this._TableNum;
			}
			set
			{
				if ((this._TableNum != value))
				{
					this.OnTableNumChanging(value);
					this.SendPropertyChanging();
					this._TableNum = value;
					this.SendPropertyChanged("TableNum");
					this.OnTableNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
