//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportMonthResultGenerator.StaffEmplSal {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters")]
    public partial class division_pay_EMPLOEE_PARAMRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> emploee_idField;
        
        private System.Nullable<int> subdivision_idField;
        
        private System.Nullable<int> position_idField;
        
        private System.Nullable<decimal> dayHourCountField;
        
        private System.Nullable<decimal> nighHourCountField;
        
        private System.Nullable<decimal> sallaryField;
        
        private System.Nullable<decimal> pAYROLL_TYPE_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> emploee_id {
            get {
                return this.emploee_idField;
            }
            set {
                this.emploee_idField = value;
                this.RaisePropertyChanged("emploee_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> subdivision_id {
            get {
                return this.subdivision_idField;
            }
            set {
                this.subdivision_idField = value;
                this.RaisePropertyChanged("subdivision_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> position_id {
            get {
                return this.position_idField;
            }
            set {
                this.position_idField = value;
                this.RaisePropertyChanged("position_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> DayHourCount {
            get {
                return this.dayHourCountField;
            }
            set {
                this.dayHourCountField = value;
                this.RaisePropertyChanged("DayHourCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> NighHourCount {
            get {
                return this.nighHourCountField;
            }
            set {
                this.nighHourCountField = value;
                this.RaisePropertyChanged("NighHourCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> sallary {
            get {
                return this.sallaryField;
            }
            set {
                this.sallaryField = value;
                this.RaisePropertyChanged("sallary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> PAYROLL_TYPE_ID {
            get {
                return this.pAYROLL_TYPE_IDField;
            }
            set {
                this.pAYROLL_TYPE_IDField = value;
                this.RaisePropertyChanged("PAYROLL_TYPE_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters")]
    public partial class division_pay_EMPLOEE_LISTRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> emploee_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> emploee_id {
            get {
                return this.emploee_idField;
            }
            set {
                this.emploee_idField = value;
                this.RaisePropertyChanged("emploee_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:coffeemanania:staffEmployee", ConfigurationName="StaffEmplSal.StaffEmployeeParametersObj")]
    public interface StaffEmployeeParametersObj {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения division_payRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.division_payResponse division_pay(ReportMonthResultGenerator.StaffEmplSal.division_payRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения GetAllEmployeeParametersRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersResponse GetAllEmployeeParameters(ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения download_imageRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.download_imageResponse download_image(ReportMonthResultGenerator.StaffEmplSal.download_imageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения Emploee_payRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.Emploee_payResponse Emploee_pay(ReportMonthResultGenerator.StaffEmplSal.Emploee_payRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения get_responseRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.get_responseResponse get_response(ReportMonthResultGenerator.StaffEmplSal.get_responseRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения MoveToUnemployedRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedResponse MoveToUnemployed(ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения person_salaryRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.person_salaryResponse person_salary(ReportMonthResultGenerator.StaffEmplSal.person_salaryRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения procedure_for_historyRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyResponse procedure_for_history(ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения PutAllEmployeeParametersRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersResponse PutAllEmployeeParameters(ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (urn:coffeemanania:staffEmployee:StaffEmployeeParameters) сообщения ReturnFromUnemployedRequest не соответствует значению по умолчанию (urn:coffeemanania:staffEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReportMonthResultGenerator.StaffEmplSal.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedResponse ReturnFromUnemployed(ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="division_pay", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class division_payRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sub_division_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SelectDATE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EMPLOEE_LISTRow", IsNullable=false)]
        public ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_LISTRow[] EMPLOEE_LIST;
        
        public division_payRequest() {
        }
        
        public division_payRequest(System.Nullable<int> sub_division_id, System.Nullable<System.DateTime> SelectDATE, ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_LISTRow[] EMPLOEE_LIST) {
            this.sub_division_id = sub_division_id;
            this.SelectDATE = SelectDATE;
            this.EMPLOEE_LIST = EMPLOEE_LIST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="division_payResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class division_payResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FOT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EMPLOEE_PARAMRow", IsNullable=false)]
        public ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_PARAMRow[] EMPLOEE_PARAM;
        
        public division_payResponse() {
        }
        
        public division_payResponse(string result, System.Nullable<decimal> FOT, ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_PARAMRow[] EMPLOEE_PARAM) {
            this.result = result;
            this.FOT = FOT;
            this.EMPLOEE_PARAM = EMPLOEE_PARAM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllEmployeeParameters", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class GetAllEmployeeParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> empId;
        
        public GetAllEmployeeParametersRequest() {
        }
        
        public GetAllEmployeeParametersRequest(System.Nullable<int> empId) {
            this.empId = empId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllEmployeeParametersResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class GetAllEmployeeParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pFirst_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pMiddle_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pLast_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_update;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_entry;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_enrol;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_dism;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pReason_dism;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPayroll_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPayroll_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pSalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_salary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPosition_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPosition_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pDivision_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pDivision_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pBirthday;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pSize_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pSex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=21)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorText;
        
        public GetAllEmployeeParametersResponse() {
        }
        
        public GetAllEmployeeParametersResponse(
                    string result, 
                    string pFirst_name, 
                    string pMiddle_name, 
                    string pLast_name, 
                    string pPhone, 
                    System.Nullable<System.DateTime> pDate_update, 
                    System.Nullable<System.DateTime> pDate_entry, 
                    System.Nullable<System.DateTime> pDate_enrol, 
                    System.Nullable<System.DateTime> pDate_dism, 
                    string pReason_dism, 
                    System.Nullable<int> pPayroll_id, 
                    string pPayroll_name, 
                    System.Nullable<decimal> pSalary, 
                    System.Nullable<System.DateTime> pDate_salary, 
                    System.Nullable<int> pPosition_id, 
                    string pPosition_name, 
                    System.Nullable<int> pDivision_id, 
                    string pDivision_name, 
                    System.Nullable<System.DateTime> pBirthday, 
                    System.Nullable<int> pSize_id, 
                    string pSex, 
                    string ErrorText) {
            this.result = result;
            this.pFirst_name = pFirst_name;
            this.pMiddle_name = pMiddle_name;
            this.pLast_name = pLast_name;
            this.pPhone = pPhone;
            this.pDate_update = pDate_update;
            this.pDate_entry = pDate_entry;
            this.pDate_enrol = pDate_enrol;
            this.pDate_dism = pDate_dism;
            this.pReason_dism = pReason_dism;
            this.pPayroll_id = pPayroll_id;
            this.pPayroll_name = pPayroll_name;
            this.pSalary = pSalary;
            this.pDate_salary = pDate_salary;
            this.pPosition_id = pPosition_id;
            this.pPosition_name = pPosition_name;
            this.pDivision_id = pDivision_id;
            this.pDivision_name = pDivision_name;
            this.pBirthday = pBirthday;
            this.pSize_id = pSize_id;
            this.pSex = pSex;
            this.ErrorText = ErrorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="download_image", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class download_imageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CurrentUserID;
        
        public download_imageRequest() {
        }
        
        public download_imageRequest(System.Nullable<int> CurrentUserID) {
            this.CurrentUserID = CurrentUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="download_imageResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class download_imageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> res;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Link_image;
        
        public download_imageResponse() {
        }
        
        public download_imageResponse(string result, System.Nullable<bool> res, byte[] Link_image) {
            this.result = result;
            this.res = res;
            this.Link_image = Link_image;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters")]
    public partial class Emploee_pay_WORKTIME_TEMPRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> emploee_idField;
        
        private System.Nullable<int> valTimeSecondField;
        
        private System.Nullable<decimal> sallaryField;
        
        private System.Nullable<decimal> pAYROLL_TYPE_IDField;
        
        private System.Nullable<decimal> pAYROLLField;
        
        private System.Nullable<System.DateTime> arrivalField;
        
        private System.Nullable<System.DateTime> departureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> emploee_id {
            get {
                return this.emploee_idField;
            }
            set {
                this.emploee_idField = value;
                this.RaisePropertyChanged("emploee_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ValTimeSecond {
            get {
                return this.valTimeSecondField;
            }
            set {
                this.valTimeSecondField = value;
                this.RaisePropertyChanged("ValTimeSecond");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> sallary {
            get {
                return this.sallaryField;
            }
            set {
                this.sallaryField = value;
                this.RaisePropertyChanged("sallary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> PAYROLL_TYPE_ID {
            get {
                return this.pAYROLL_TYPE_IDField;
            }
            set {
                this.pAYROLL_TYPE_IDField = value;
                this.RaisePropertyChanged("PAYROLL_TYPE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> PAYROLL {
            get {
                return this.pAYROLLField;
            }
            set {
                this.pAYROLLField = value;
                this.RaisePropertyChanged("PAYROLL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
                this.RaisePropertyChanged("arrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
                this.RaisePropertyChanged("departure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Emploee_pay", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class Emploee_payRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> sub_division_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateDay;
        
        public Emploee_payRequest() {
        }
        
        public Emploee_payRequest(System.Nullable<int> sub_division_id, System.Nullable<System.DateTime> DateDay) {
            this.sub_division_id = sub_division_id;
            this.DateDay = DateDay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Emploee_payResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class Emploee_payResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WORKTIME_TEMPRow", IsNullable=false)]
        public ReportMonthResultGenerator.StaffEmplSal.Emploee_pay_WORKTIME_TEMPRow[] WORKTIME_TEMP;
        
        public Emploee_payResponse() {
        }
        
        public Emploee_payResponse(string result, ReportMonthResultGenerator.StaffEmplSal.Emploee_pay_WORKTIME_TEMPRow[] WORKTIME_TEMP) {
            this.result = result;
            this.WORKTIME_TEMP = WORKTIME_TEMP;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters")]
    public partial class get_response_t_RESPONSERow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> response_idField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private System.Nullable<int> user_idField;
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> response_id {
            get {
                return this.response_idField;
            }
            set {
                this.response_idField = value;
                this.RaisePropertyChanged("response_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_response", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class get_responseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> varEmployeeId;
        
        public get_responseRequest() {
        }
        
        public get_responseRequest(System.Nullable<int> varEmployeeId) {
            this.varEmployeeId = varEmployeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_responseResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class get_responseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("t_RESPONSERow", IsNullable=false)]
        public ReportMonthResultGenerator.StaffEmplSal.get_response_t_RESPONSERow[] t_RESPONSE;
        
        public get_responseResponse() {
        }
        
        public get_responseResponse(string result, ReportMonthResultGenerator.StaffEmplSal.get_response_t_RESPONSERow[] t_RESPONSE) {
            this.result = result;
            this.t_RESPONSE = t_RESPONSE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveToUnemployed", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class MoveToUnemployedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> empid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> MOVE_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MOVE_reason;
        
        public MoveToUnemployedRequest() {
        }
        
        public MoveToUnemployedRequest(System.Nullable<int> empid, System.Nullable<System.DateTime> MOVE_date, string MOVE_reason) {
            this.empid = empid;
            this.MOVE_date = MOVE_date;
            this.MOVE_reason = MOVE_reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveToUnemployedResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class MoveToUnemployedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        public MoveToUnemployedResponse() {
        }
        
        public MoveToUnemployedResponse(string result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="person_salary", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class person_salaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> p_employee_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> p_subdivision_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> p_position_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> p_month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> p_year;
        
        public person_salaryRequest() {
        }
        
        public person_salaryRequest(System.Nullable<int> p_employee_id, System.Nullable<int> p_subdivision_id, System.Nullable<int> p_position_id, System.Nullable<int> p_month, System.Nullable<int> p_year) {
            this.p_employee_id = p_employee_id;
            this.p_subdivision_id = p_subdivision_id;
            this.p_position_id = p_position_id;
            this.p_month = p_month;
            this.p_year = p_year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="person_salaryResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class person_salaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_RESULT;
        
        public person_salaryResponse() {
        }
        
        public person_salaryResponse(string result, System.Nullable<decimal> P_RESULT) {
            this.result = result;
            this.P_RESULT = P_RESULT;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters")]
    public partial class procedure_for_history_t_emphistoryRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> employee_idField;
        
        private System.Nullable<int> position_idField;
        
        private System.Nullable<int> subdivision_idField;
        
        private string position_nameField;
        
        private string subdivision_nameField;
        
        private System.Nullable<System.DateTime> work_from_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> employee_id {
            get {
                return this.employee_idField;
            }
            set {
                this.employee_idField = value;
                this.RaisePropertyChanged("employee_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> position_id {
            get {
                return this.position_idField;
            }
            set {
                this.position_idField = value;
                this.RaisePropertyChanged("position_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> subdivision_id {
            get {
                return this.subdivision_idField;
            }
            set {
                this.subdivision_idField = value;
                this.RaisePropertyChanged("subdivision_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string position_name {
            get {
                return this.position_nameField;
            }
            set {
                this.position_nameField = value;
                this.RaisePropertyChanged("position_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string subdivision_name {
            get {
                return this.subdivision_nameField;
            }
            set {
                this.subdivision_nameField = value;
                this.RaisePropertyChanged("subdivision_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> work_from_date {
            get {
                return this.work_from_dateField;
            }
            set {
                this.work_from_dateField = value;
                this.RaisePropertyChanged("work_from_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procedure_for_history", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class procedure_for_historyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> varEmployeeId;
        
        public procedure_for_historyRequest() {
        }
        
        public procedure_for_historyRequest(System.Nullable<int> varEmployeeId) {
            this.varEmployeeId = varEmployeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procedure_for_historyResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class procedure_for_historyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("t_emphistoryRow", IsNullable=false)]
        public ReportMonthResultGenerator.StaffEmplSal.procedure_for_history_t_emphistoryRow[] t_emphistory;
        
        public procedure_for_historyResponse() {
        }
        
        public procedure_for_historyResponse(string result, ReportMonthResultGenerator.StaffEmplSal.procedure_for_history_t_emphistoryRow[] t_emphistory) {
            this.result = result;
            this.t_emphistory = t_emphistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAllEmployeeParameters", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class PutAllEmployeeParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> empId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pFirst_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pMiddle_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pLast_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_entry;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_enrol;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_dism;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pReason_dism;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPayroll_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pSalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pDate_salary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPosition_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pDivision_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> pBirthday;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pSize_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pSex;
        
        public PutAllEmployeeParametersRequest() {
        }
        
        public PutAllEmployeeParametersRequest(
                    System.Nullable<int> empId, 
                    string pFirst_name, 
                    string pMiddle_name, 
                    string pLast_name, 
                    string pPhone, 
                    System.Nullable<System.DateTime> pDate_entry, 
                    System.Nullable<System.DateTime> pDate_enrol, 
                    System.Nullable<System.DateTime> pDate_dism, 
                    string pReason_dism, 
                    System.Nullable<int> pPayroll_id, 
                    System.Nullable<decimal> pSalary, 
                    System.Nullable<System.DateTime> pDate_salary, 
                    System.Nullable<int> pPosition_id, 
                    System.Nullable<int> pDivision_id, 
                    System.Nullable<System.DateTime> pBirthday, 
                    System.Nullable<int> pSize_id, 
                    string pSex) {
            this.empId = empId;
            this.pFirst_name = pFirst_name;
            this.pMiddle_name = pMiddle_name;
            this.pLast_name = pLast_name;
            this.pPhone = pPhone;
            this.pDate_entry = pDate_entry;
            this.pDate_enrol = pDate_enrol;
            this.pDate_dism = pDate_dism;
            this.pReason_dism = pReason_dism;
            this.pPayroll_id = pPayroll_id;
            this.pSalary = pSalary;
            this.pDate_salary = pDate_salary;
            this.pPosition_id = pPosition_id;
            this.pDivision_id = pDivision_id;
            this.pBirthday = pBirthday;
            this.pSize_id = pSize_id;
            this.pSex = pSex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAllEmployeeParametersResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class PutAllEmployeeParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NewEmpId;
        
        public PutAllEmployeeParametersResponse() {
        }
        
        public PutAllEmployeeParametersResponse(string result, string ErrorText, System.Nullable<int> NewEmpId) {
            this.result = result;
            this.ErrorText = ErrorText;
            this.NewEmpId = NewEmpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnFromUnemployed", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class ReturnFromUnemployedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> empid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> MOVE_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPayroll_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pSalary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pPosition_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pDivision_id;
        
        public ReturnFromUnemployedRequest() {
        }
        
        public ReturnFromUnemployedRequest(System.Nullable<int> empid, System.Nullable<System.DateTime> MOVE_date, System.Nullable<int> pPayroll_id, System.Nullable<decimal> pSalary, System.Nullable<int> pPosition_id, System.Nullable<int> pDivision_id) {
            this.empid = empid;
            this.MOVE_date = MOVE_date;
            this.pPayroll_id = pPayroll_id;
            this.pSalary = pSalary;
            this.pPosition_id = pPosition_id;
            this.pDivision_id = pDivision_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnFromUnemployedResponse", WrapperNamespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", IsWrapped=true)]
    public partial class ReturnFromUnemployedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:coffeemanania:staffEmployee:StaffEmployeeParameters", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        public ReturnFromUnemployedResponse() {
        }
        
        public ReturnFromUnemployedResponse(string result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StaffEmployeeParametersObjChannel : ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffEmployeeParametersObjClient : System.ServiceModel.ClientBase<ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj>, ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj {
        
        public StaffEmployeeParametersObjClient() {
        }
        
        public StaffEmployeeParametersObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffEmployeeParametersObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffEmployeeParametersObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffEmployeeParametersObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.division_payResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.division_pay(ReportMonthResultGenerator.StaffEmplSal.division_payRequest request) {
            return base.Channel.division_pay(request);
        }
        
        public string division_pay(System.Nullable<int> sub_division_id, System.Nullable<System.DateTime> SelectDATE, ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_LISTRow[] EMPLOEE_LIST, out System.Nullable<decimal> FOT, out ReportMonthResultGenerator.StaffEmplSal.division_pay_EMPLOEE_PARAMRow[] EMPLOEE_PARAM) {
            ReportMonthResultGenerator.StaffEmplSal.division_payRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.division_payRequest();
            inValue.sub_division_id = sub_division_id;
            inValue.SelectDATE = SelectDATE;
            inValue.EMPLOEE_LIST = EMPLOEE_LIST;
            ReportMonthResultGenerator.StaffEmplSal.division_payResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).division_pay(inValue);
            FOT = retVal.FOT;
            EMPLOEE_PARAM = retVal.EMPLOEE_PARAM;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.GetAllEmployeeParameters(ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersRequest request) {
            return base.Channel.GetAllEmployeeParameters(request);
        }
        
        public string GetAllEmployeeParameters(
                    System.Nullable<int> empId, 
                    out string pFirst_name, 
                    out string pMiddle_name, 
                    out string pLast_name, 
                    out string pPhone, 
                    out System.Nullable<System.DateTime> pDate_update, 
                    out System.Nullable<System.DateTime> pDate_entry, 
                    out System.Nullable<System.DateTime> pDate_enrol, 
                    out System.Nullable<System.DateTime> pDate_dism, 
                    out string pReason_dism, 
                    out System.Nullable<int> pPayroll_id, 
                    out string pPayroll_name, 
                    out System.Nullable<decimal> pSalary, 
                    out System.Nullable<System.DateTime> pDate_salary, 
                    out System.Nullable<int> pPosition_id, 
                    out string pPosition_name, 
                    out System.Nullable<int> pDivision_id, 
                    out string pDivision_name, 
                    out System.Nullable<System.DateTime> pBirthday, 
                    out System.Nullable<int> pSize_id, 
                    out string pSex, 
                    out string ErrorText) {
            ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersRequest();
            inValue.empId = empId;
            ReportMonthResultGenerator.StaffEmplSal.GetAllEmployeeParametersResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).GetAllEmployeeParameters(inValue);
            pFirst_name = retVal.pFirst_name;
            pMiddle_name = retVal.pMiddle_name;
            pLast_name = retVal.pLast_name;
            pPhone = retVal.pPhone;
            pDate_update = retVal.pDate_update;
            pDate_entry = retVal.pDate_entry;
            pDate_enrol = retVal.pDate_enrol;
            pDate_dism = retVal.pDate_dism;
            pReason_dism = retVal.pReason_dism;
            pPayroll_id = retVal.pPayroll_id;
            pPayroll_name = retVal.pPayroll_name;
            pSalary = retVal.pSalary;
            pDate_salary = retVal.pDate_salary;
            pPosition_id = retVal.pPosition_id;
            pPosition_name = retVal.pPosition_name;
            pDivision_id = retVal.pDivision_id;
            pDivision_name = retVal.pDivision_name;
            pBirthday = retVal.pBirthday;
            pSize_id = retVal.pSize_id;
            pSex = retVal.pSex;
            ErrorText = retVal.ErrorText;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.download_imageResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.download_image(ReportMonthResultGenerator.StaffEmplSal.download_imageRequest request) {
            return base.Channel.download_image(request);
        }
        
        public string download_image(System.Nullable<int> CurrentUserID, out System.Nullable<bool> res, out byte[] Link_image) {
            ReportMonthResultGenerator.StaffEmplSal.download_imageRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.download_imageRequest();
            inValue.CurrentUserID = CurrentUserID;
            ReportMonthResultGenerator.StaffEmplSal.download_imageResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).download_image(inValue);
            res = retVal.res;
            Link_image = retVal.Link_image;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.Emploee_payResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.Emploee_pay(ReportMonthResultGenerator.StaffEmplSal.Emploee_payRequest request) {
            return base.Channel.Emploee_pay(request);
        }
        
        public string Emploee_pay(System.Nullable<int> sub_division_id, System.Nullable<System.DateTime> DateDay, out ReportMonthResultGenerator.StaffEmplSal.Emploee_pay_WORKTIME_TEMPRow[] WORKTIME_TEMP) {
            ReportMonthResultGenerator.StaffEmplSal.Emploee_payRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.Emploee_payRequest();
            inValue.sub_division_id = sub_division_id;
            inValue.DateDay = DateDay;
            ReportMonthResultGenerator.StaffEmplSal.Emploee_payResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).Emploee_pay(inValue);
            WORKTIME_TEMP = retVal.WORKTIME_TEMP;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.get_responseResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.get_response(ReportMonthResultGenerator.StaffEmplSal.get_responseRequest request) {
            return base.Channel.get_response(request);
        }
        
        public string get_response(System.Nullable<int> varEmployeeId, out ReportMonthResultGenerator.StaffEmplSal.get_response_t_RESPONSERow[] t_RESPONSE) {
            ReportMonthResultGenerator.StaffEmplSal.get_responseRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.get_responseRequest();
            inValue.varEmployeeId = varEmployeeId;
            ReportMonthResultGenerator.StaffEmplSal.get_responseResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).get_response(inValue);
            t_RESPONSE = retVal.t_RESPONSE;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.MoveToUnemployed(ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedRequest request) {
            return base.Channel.MoveToUnemployed(request);
        }
        
        public string MoveToUnemployed(System.Nullable<int> empid, System.Nullable<System.DateTime> MOVE_date, string MOVE_reason) {
            ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedRequest();
            inValue.empid = empid;
            inValue.MOVE_date = MOVE_date;
            inValue.MOVE_reason = MOVE_reason;
            ReportMonthResultGenerator.StaffEmplSal.MoveToUnemployedResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).MoveToUnemployed(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.person_salaryResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.person_salary(ReportMonthResultGenerator.StaffEmplSal.person_salaryRequest request) {
            return base.Channel.person_salary(request);
        }
        
        public string person_salary(System.Nullable<int> p_employee_id, System.Nullable<int> p_subdivision_id, System.Nullable<int> p_position_id, System.Nullable<int> p_month, System.Nullable<int> p_year, out System.Nullable<decimal> P_RESULT) {
            ReportMonthResultGenerator.StaffEmplSal.person_salaryRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.person_salaryRequest();
            inValue.p_employee_id = p_employee_id;
            inValue.p_subdivision_id = p_subdivision_id;
            inValue.p_position_id = p_position_id;
            inValue.p_month = p_month;
            inValue.p_year = p_year;
            ReportMonthResultGenerator.StaffEmplSal.person_salaryResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).person_salary(inValue);
            P_RESULT = retVal.P_RESULT;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.procedure_for_history(ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyRequest request) {
            return base.Channel.procedure_for_history(request);
        }
        
        public string procedure_for_history(System.Nullable<int> varEmployeeId, out ReportMonthResultGenerator.StaffEmplSal.procedure_for_history_t_emphistoryRow[] t_emphistory) {
            ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyRequest();
            inValue.varEmployeeId = varEmployeeId;
            ReportMonthResultGenerator.StaffEmplSal.procedure_for_historyResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).procedure_for_history(inValue);
            t_emphistory = retVal.t_emphistory;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.PutAllEmployeeParameters(ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersRequest request) {
            return base.Channel.PutAllEmployeeParameters(request);
        }
        
        public string PutAllEmployeeParameters(
                    System.Nullable<int> empId, 
                    string pFirst_name, 
                    string pMiddle_name, 
                    string pLast_name, 
                    string pPhone, 
                    System.Nullable<System.DateTime> pDate_entry, 
                    System.Nullable<System.DateTime> pDate_enrol, 
                    System.Nullable<System.DateTime> pDate_dism, 
                    string pReason_dism, 
                    System.Nullable<int> pPayroll_id, 
                    System.Nullable<decimal> pSalary, 
                    System.Nullable<System.DateTime> pDate_salary, 
                    System.Nullable<int> pPosition_id, 
                    System.Nullable<int> pDivision_id, 
                    System.Nullable<System.DateTime> pBirthday, 
                    System.Nullable<int> pSize_id, 
                    string pSex, 
                    out string ErrorText, 
                    out System.Nullable<int> NewEmpId) {
            ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersRequest();
            inValue.empId = empId;
            inValue.pFirst_name = pFirst_name;
            inValue.pMiddle_name = pMiddle_name;
            inValue.pLast_name = pLast_name;
            inValue.pPhone = pPhone;
            inValue.pDate_entry = pDate_entry;
            inValue.pDate_enrol = pDate_enrol;
            inValue.pDate_dism = pDate_dism;
            inValue.pReason_dism = pReason_dism;
            inValue.pPayroll_id = pPayroll_id;
            inValue.pSalary = pSalary;
            inValue.pDate_salary = pDate_salary;
            inValue.pPosition_id = pPosition_id;
            inValue.pDivision_id = pDivision_id;
            inValue.pBirthday = pBirthday;
            inValue.pSize_id = pSize_id;
            inValue.pSex = pSex;
            ReportMonthResultGenerator.StaffEmplSal.PutAllEmployeeParametersResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).PutAllEmployeeParameters(inValue);
            ErrorText = retVal.ErrorText;
            NewEmpId = retVal.NewEmpId;
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedResponse ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj.ReturnFromUnemployed(ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedRequest request) {
            return base.Channel.ReturnFromUnemployed(request);
        }
        
        public string ReturnFromUnemployed(System.Nullable<int> empid, System.Nullable<System.DateTime> MOVE_date, System.Nullable<int> pPayroll_id, System.Nullable<decimal> pSalary, System.Nullable<int> pPosition_id, System.Nullable<int> pDivision_id) {
            ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedRequest inValue = new ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedRequest();
            inValue.empid = empid;
            inValue.MOVE_date = MOVE_date;
            inValue.pPayroll_id = pPayroll_id;
            inValue.pSalary = pSalary;
            inValue.pPosition_id = pPosition_id;
            inValue.pDivision_id = pDivision_id;
            ReportMonthResultGenerator.StaffEmplSal.ReturnFromUnemployedResponse retVal = ((ReportMonthResultGenerator.StaffEmplSal.StaffEmployeeParametersObj)(this)).ReturnFromUnemployed(inValue);
            return retVal.result;
        }
    }
}
