//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ReportMonthResultGenerator.vfiliasut8 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExchangePeskovFotoGallerySoapBinding", Namespace="ExchangePeskovFotoGallery")]
    public partial class ExchangePeskovFotoGallery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCostsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCosts_testOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCostsList_testOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaharListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCostsGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExchangePeskovFotoGallery() {
            this.Url = global::ReportMonthResultGenerator.Properties.Settings.Default.ReportMonthResultGenerator_vfiliasut8_ExchangePeskovFotoGallery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCostsCompletedEventHandler getCostsCompleted;
        
        /// <remarks/>
        public event getCostsListCompletedEventHandler getCostsListCompleted;
        
        /// <remarks/>
        public event getCosts_testCompletedEventHandler getCosts_testCompleted;
        
        /// <remarks/>
        public event getCostsList_testCompletedEventHandler getCostsList_testCompleted;
        
        /// <remarks/>
        public event GetPaharListCompletedEventHandler GetPaharListCompleted;
        
        /// <remarks/>
        public event getCostsGroupCompletedEventHandler getCostsGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:getCosts", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public double getCosts([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("getCosts", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getCostsAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.getCostsAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void getCostsAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.getCostsOperationCompleted == null)) {
                this.getCostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCostsOperationCompleted);
            }
            this.InvokeAsync("getCosts", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.getCostsOperationCompleted, userState);
        }
        
        private void OngetCostsOperationCompleted(object arg) {
            if ((this.getCostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCostsCompleted(this, new getCostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:getCostsList", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getCostsList([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("getCostsList", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCostsListAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.getCostsListAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void getCostsListAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.getCostsListOperationCompleted == null)) {
                this.getCostsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCostsListOperationCompleted);
            }
            this.InvokeAsync("getCostsList", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.getCostsListOperationCompleted, userState);
        }
        
        private void OngetCostsListOperationCompleted(object arg) {
            if ((this.getCostsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCostsListCompleted(this, new getCostsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:getCosts_test", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public double getCosts_test([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("getCosts_test", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getCosts_testAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.getCosts_testAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void getCosts_testAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.getCosts_testOperationCompleted == null)) {
                this.getCosts_testOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCosts_testOperationCompleted);
            }
            this.InvokeAsync("getCosts_test", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.getCosts_testOperationCompleted, userState);
        }
        
        private void OngetCosts_testOperationCompleted(object arg) {
            if ((this.getCosts_testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCosts_testCompleted(this, new getCosts_testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:getCostsList_test", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getCostsList_test([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("getCostsList_test", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCostsList_testAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.getCostsList_testAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void getCostsList_testAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.getCostsList_testOperationCompleted == null)) {
                this.getCostsList_testOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCostsList_testOperationCompleted);
            }
            this.InvokeAsync("getCostsList_test", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.getCostsList_testOperationCompleted, userState);
        }
        
        private void OngetCostsList_testOperationCompleted(object arg) {
            if ((this.getCostsList_testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCostsList_testCompleted(this, new getCostsList_testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:GetPaharList", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string GetPaharList([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("GetPaharList", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaharListAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.GetPaharListAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void GetPaharListAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.GetPaharListOperationCompleted == null)) {
                this.GetPaharListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaharListOperationCompleted);
            }
            this.InvokeAsync("GetPaharList", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.GetPaharListOperationCompleted, userState);
        }
        
        private void OnGetPaharListOperationCompleted(object arg) {
            if ((this.GetPaharListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaharListCompleted(this, new GetPaharListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExchangePeskovFotoGallery#ExchangePeskovFotoGallery:getCostsGroup", RequestNamespace="ExchangePeskovFotoGallery", ResponseNamespace="ExchangePeskovFotoGallery", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getCostsGroup([System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string codeUnion, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateStart, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime dateEnd) {
            object[] results = this.Invoke("getCostsGroup", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCostsGroupAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd) {
            this.getCostsGroupAsync(codeUnion, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void getCostsGroupAsync(string codeUnion, System.DateTime dateStart, System.DateTime dateEnd, object userState) {
            if ((this.getCostsGroupOperationCompleted == null)) {
                this.getCostsGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCostsGroupOperationCompleted);
            }
            this.InvokeAsync("getCostsGroup", new object[] {
                        codeUnion,
                        dateStart,
                        dateEnd}, this.getCostsGroupOperationCompleted, userState);
        }
        
        private void OngetCostsGroupOperationCompleted(object arg) {
            if ((this.getCostsGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCostsGroupCompleted(this, new getCostsGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getCostsCompletedEventHandler(object sender, getCostsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getCostsListCompletedEventHandler(object sender, getCostsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCostsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCostsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getCosts_testCompletedEventHandler(object sender, getCosts_testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCosts_testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCosts_testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getCostsList_testCompletedEventHandler(object sender, getCostsList_testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCostsList_testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCostsList_testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPaharListCompletedEventHandler(object sender, GetPaharListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaharListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaharListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getCostsGroupCompletedEventHandler(object sender, getCostsGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCostsGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCostsGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591