//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportMonthResultGenerator.SrvOrderTimes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTimes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderTimes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private System.Nullable<int> ItemCookTimeField;
        
        private System.Nullable<int> TransactionNumberField;
        
        private System.Nullable<int> ItemNumberField;
        
        private System.Nullable<int> ItemIdField;
        
        private System.Nullable<int> OrderFirstDisplayedTimeField;
        
        private System.Nullable<int> OrderLastBumpTimeField;
        
        private System.Nullable<int> VirtualDisplayIdField;
        
        private System.Nullable<int> ServerIdField;
        
        private System.Nullable<System.DateTime> OrderStartTimeField;
        
        private System.Nullable<int> DepField;
        
        private System.Nullable<System.DateTime> BusinessDateField;
        
        private System.Nullable<System.DateTime> OrderEndTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ItemCookTime {
            get {
                return this.ItemCookTimeField;
            }
            set {
                if ((this.ItemCookTimeField.Equals(value) != true)) {
                    this.ItemCookTimeField = value;
                    this.RaisePropertyChanged("ItemCookTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((this.TransactionNumberField.Equals(value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((this.ItemNumberField.Equals(value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> OrderFirstDisplayedTime {
            get {
                return this.OrderFirstDisplayedTimeField;
            }
            set {
                if ((this.OrderFirstDisplayedTimeField.Equals(value) != true)) {
                    this.OrderFirstDisplayedTimeField = value;
                    this.RaisePropertyChanged("OrderFirstDisplayedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> OrderLastBumpTime {
            get {
                return this.OrderLastBumpTimeField;
            }
            set {
                if ((this.OrderLastBumpTimeField.Equals(value) != true)) {
                    this.OrderLastBumpTimeField = value;
                    this.RaisePropertyChanged("OrderLastBumpTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> VirtualDisplayId {
            get {
                return this.VirtualDisplayIdField;
            }
            set {
                if ((this.VirtualDisplayIdField.Equals(value) != true)) {
                    this.VirtualDisplayIdField = value;
                    this.RaisePropertyChanged("VirtualDisplayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> ServerId {
            get {
                return this.ServerIdField;
            }
            set {
                if ((this.ServerIdField.Equals(value) != true)) {
                    this.ServerIdField = value;
                    this.RaisePropertyChanged("ServerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> OrderStartTime {
            get {
                return this.OrderStartTimeField;
            }
            set {
                if ((this.OrderStartTimeField.Equals(value) != true)) {
                    this.OrderStartTimeField = value;
                    this.RaisePropertyChanged("OrderStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> Dep {
            get {
                return this.DepField;
            }
            set {
                if ((this.DepField.Equals(value) != true)) {
                    this.DepField = value;
                    this.RaisePropertyChanged("Dep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> BusinessDate {
            get {
                return this.BusinessDateField;
            }
            set {
                if ((this.BusinessDateField.Equals(value) != true)) {
                    this.BusinessDateField = value;
                    this.RaisePropertyChanged("BusinessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<System.DateTime> OrderEndTime {
            get {
                return this.OrderEndTimeField;
            }
            set {
                if ((this.OrderEndTimeField.Equals(value) != true)) {
                    this.OrderEndTimeField = value;
                    this.RaisePropertyChanged("OrderEndTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddOrderTimeResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AddOrderTimeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private bool ExistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool Exists {
            get {
                return this.ExistsField;
            }
            set {
                if ((this.ExistsField.Equals(value) != true)) {
                    this.ExistsField = value;
                    this.RaisePropertyChanged("Exists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrMsg {
            get {
                return this.ErrMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMsgField, value) != true)) {
                    this.ErrMsgField = value;
                    this.RaisePropertyChanged("ErrMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvOrderTimes.SrvOrderTimes2Soap")]
    public interface SrvOrderTimes2Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем record из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrderTimes", ReplyAction="*")]
        ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesResponse AddOrderTimes(ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderTimesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderTimes", Namespace="http://tempuri.org/", Order=0)]
        public ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequestBody Body;
        
        public AddOrderTimesRequest() {
        }
        
        public AddOrderTimesRequest(ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderTimesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportMonthResultGenerator.SrvOrderTimes.OrderTimes record;
        
        public AddOrderTimesRequestBody() {
        }
        
        public AddOrderTimesRequestBody(ReportMonthResultGenerator.SrvOrderTimes.OrderTimes record) {
            this.record = record;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderTimesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderTimesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesResponseBody Body;
        
        public AddOrderTimesResponse() {
        }
        
        public AddOrderTimesResponse(ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderTimesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimeResult AddOrderTimesResult;
        
        public AddOrderTimesResponseBody() {
        }
        
        public AddOrderTimesResponseBody(ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimeResult AddOrderTimesResult) {
            this.AddOrderTimesResult = AddOrderTimesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SrvOrderTimes2SoapChannel : ReportMonthResultGenerator.SrvOrderTimes.SrvOrderTimes2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvOrderTimes2SoapClient : System.ServiceModel.ClientBase<ReportMonthResultGenerator.SrvOrderTimes.SrvOrderTimes2Soap>, ReportMonthResultGenerator.SrvOrderTimes.SrvOrderTimes2Soap {
        
        public SrvOrderTimes2SoapClient() {
        }
        
        public SrvOrderTimes2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvOrderTimes2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvOrderTimes2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvOrderTimes2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesResponse ReportMonthResultGenerator.SrvOrderTimes.SrvOrderTimes2Soap.AddOrderTimes(ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequest request) {
            return base.Channel.AddOrderTimes(request);
        }
        
        public ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimeResult AddOrderTimes(ReportMonthResultGenerator.SrvOrderTimes.OrderTimes record) {
            ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequest inValue = new ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequest();
            inValue.Body = new ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesRequestBody();
            inValue.Body.record = record;
            ReportMonthResultGenerator.SrvOrderTimes.AddOrderTimesResponse retVal = ((ReportMonthResultGenerator.SrvOrderTimes.SrvOrderTimes2Soap)(this)).AddOrderTimes(inValue);
            return retVal.Body.AddOrderTimesResult;
        }
    }
}
